---
- hosts: all
  become: yes
# install, enable and restart apache2
  tasks:
    - name: install apache2
      apt:
          name: apache2
          update_cache: yes
          state: present
    - name: enable and restart apache2
      service:
          enabbled: yes
          state: restarted
# install php and modules
    - name: install php
      yum:
          name: install php
          state: present
    - name: install libapache2-mod-php
      yum:
          name: libapache2-mod-php
          state: present
    - name: install php-cli
      yum: 
         name : install php-cli
         state: present
# restart apache2 
    - service:   
      name: restart apache2
      state: restarted
   

    
